### ISSUE TITLE
Specify a Vary: Accept-Encoding header

### ISSUE THREAD

**Issue by hdaraujo** [samaxes/javaee-cache-filter#2]
Chrome page speed suggests using this header to avoid issues with public proxies that do not detect the presence of a Content-Encoding header properly. See https://developers.google.com/speed/docs/best-practices/caching#LeverageProxyCaching

**Comment by samaxes** [comment]
Why not go even further and set `Vary` HTTP header with the value `Accept, Accept-Language, Accept-Encoding`?

Some examples why the directives `Accept` and `Accept-Language` can also be useful:
- `Accept` header can be used to defined if you want a REST service response to be sent in `application/json` or `application/xml` formats.
- `Accept-Language` header can be used in applications which support internationalization to select the language of the resource to get.

Read more about it at [Vary Header for RESTful Applications](http://www.subbu.org/blog/2007/12/vary-header-for-restful-applications).

WDYT?

**Comment by hdaraujo** [comment]
I'm not sure anymore that this configuration belongs to a cache filter.
Nginx, for example, does it in the gzip module with gzip_vary.

Maybe a better option would be to extend to a suite of JEE filters with
more utilities, independent from the container, something I believe is
lacking right now.

**Comment by samaxes** [comment]
Support for `Vary` HTTP header in `CacheFilter` responses has been added to version 2.3.0.
Please take a look at the [CacheFilter wiki page](../wiki/CacheFilter) and tell me what you think.
